spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/monitoria"
    username: postgres
    password: 123

jwt:
  expiration: 86400000 # 24 horas
  secret: jwt-dev-secret