spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/monitoria"
    username: postgres
    password: 123

aws:
  sqs:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    queue:
      url: https://sqs.us-east-1.amazonaws.com/075970593276/monitoria_emails.fifo