spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/monitoria"
    username: postgres
    password: 123

jwt:
  expiration: 86400000
  secret: jwt-dev-secret

aws:
  region: sa-east-1
  sns:
    topic:
      product:
        events:
          arn: arn:aws:sns:sa-east-1:075970593276:cadastro-usuario:037aa884-42bf-4505-8245-f2db731d42a9