-- Inserindo perfis de usuario
INSERT INTO PERFIL VALUES ((SELECT NEXTVAL('SEQUENCE_ID_PERFIL')), 'ADMIN');
INSERT INTO PERFIL VALUES ((SELECT NEXTVAL('SEQUENCE_ID_PERFIL')), 'COORDENADOR');
INSERT INTO PERFIL VALUES ((SELECT NEXTVAL('SEQUENCE_ID_PERFIL')), 'ALUNO');
--
--
-- Senha: 123456
-- $2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu
-- Hasheada com BCrypt. Secret dev está no application.yml
--
--
-- Inserindo usuario admin do sistema
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'tales.11.98@gmail.com', '20171370011', 'Tales Araujo', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ADMIN'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'tales.11.98@gmail.com'));
--
-- Inserindo 1 coordenador
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'thiago_moura_coord@gmail.com', '20151370000', 'Thiago Moura', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'COORDENADOR'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
--
-- Inserindo alguns alunos
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'paulo_elias01@gmail.com', '20221370001', 'Paulo Elias', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'paulo_elias01@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'roosevelt_henrique02@gmail.com', '20221370002', 'Roosevelt Henrique', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'roosevelt_henrique02@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'adriana_albuquerque03@gmail.com', '20221370003', 'Adriana Albuquerque', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'adriana_albuquerque03@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'pedro_da_costa04@gmail.com', '20221370004', 'Pedro da Costa', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'pedro_da_costa04@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'alecsander_camilo05@gmail.com', '20221370005', 'Alecsander Camilo', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'alecsander_camilo05@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'danilo_marques06@gmail.com', '20221370006', 'Danilo Marques', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'danilo_marques06@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'amarildo_pereira07@gmail.com', '20221370007', 'Amarildo Pereira', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'amarildo_pereira07@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'jefferson_marcelo08@gmail.com', '20221370008', 'Jefferson Marcelo', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'jefferson_marcelo08@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'jose_raimundo09@gmail.com', '2022137009', 'José Raimundo', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'jose_raimundo09@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'lucian_hendyo10@gmail.com', '20221370010', 'Lucian Hendyo', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'lucian_hendyo10@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'marianna_alves11@gmail.com', '20221370011', 'Marianna Alves', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'marianna_alves11@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'christopher_silva12@gmail.com', '20221370012', 'Christopher Silva', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'christopher_silva12@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'andreia_de_lima13@gmail.com', '20221370013', 'Andréia de Lima', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'andreia_de_lima13@gmail.com'));
INSERT INTO USUARIO VALUES ((SELECT NEXTVAL('SEQUENCE_ID_USUARIO')), '2022-05-11', '1998-10-11', 'josilete_rodrigues14@gmail.com', '20221370014', 'Josilete Rodrigues', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'josilete_rodrigues14@gmail.com'));

-- Inserindo um edital com data de inicio hoje e data de fim daqui 7 dias
INSERT INTO EDITAL VALUES ((SELECT NEXTVAL('SEQUENCE_ID_EDITAL')), CURRENT_DATE + 7, CURRENT_DATE, '2022.2', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));

-- Inserindo algumas vagas
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'ALGORITMOS E PROGRAMAÇÃO ESTRUTURADA', '1', FALSE, 2, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'BANCO DE DADOS I', '2', FALSE, 2, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'LEGISLAÇÃO SOCIAL', '4', FALSE, 1, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'LINGUAGENS DE MARCAÇÃO', '1', FALSE, 2, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'LINGUAGENS DE SCRIPT', '2', FALSE, 2, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'PERSISTÊNCIA DE OBJETOS', '4', FALSE, 1, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'PROGRAMAÇAO ORIENTADA A OBJETOS', '3', FALSE, 1, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));
INSERT INTO VAGA VALUES((SELECT NEXTVAL('SEQUENCE_ID_VAGA')), 'SISTEMAS OPERACIONAIS', '2', FALSE, 2, (SELECT ID FROM EDITAL WHERE SEMESTRE LIKE '2022.2'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'thiago_moura_coord@gmail.com'));

-- Inserindo as inscrições
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 98.00, CURRENT_DATE-1, 99.40, 100, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'paulo_elias01@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 91.92, CURRENT_DATE-1, 97.58, 100, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'roosevelt_henrique02@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 91.17, CURRENT_DATE-1, 95.95, 98, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'adriana_albuquerque03@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 90.64, CURRENT_DATE-1, 95.79, 98, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'pedro_da_costa04@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 83.91, CURRENT_DATE-1, 93.77, 98, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'alecsander_camilo05@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 84.51, CURRENT_DATE-1, 89.05, 91, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'danilo_marques06@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 43.67, CURRENT_DATE-1, 66.30, 76, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'amarildo_pereira07@gmail.com'), 1);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 82.91, CURRENT_DATE-1, 87.17, 89, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'jefferson_marcelo08@gmail.com'), 2);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 73.21, CURRENT_DATE-1, 82.86, 87, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'jose_raimundo09@gmail.com'), 2);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 74.82, CURRENT_DATE-1, 92.45, 100, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'lucian_hendyo10@gmail.com'), 3);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 55.91, CURRENT_DATE-1, 79.77, 90, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'marianna_alves11@gmail.com'), 3);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 98.00, CURRENT_DATE-1, 99.40, 100, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'paulo_elias01@gmail.com'), 4);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 90.64, CURRENT_DATE-1, 95.79, 98, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'pedro_da_costa04@gmail.com'), 4);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 89.34, CURRENT_DATE-1, 90.50, 91, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'christopher_silva12@gmail.com'), 4);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 91.92, CURRENT_DATE-1, 88.48, 87, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'roosevelt_henrique02@gmail.com'), 4);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 74.82, CURRENT_DATE-1, 84.05, 88, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'lucian_hendyo10@gmail.com'), 4);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 43.67, CURRENT_DATE-1, 83.10, 100, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'amarildo_pereira07@gmail.com'), 4);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 84.51, CURRENT_DATE-1, 95.35, 100, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'danilo_marques06@gmail.com'), 5);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 82.91, CURRENT_DATE-1, 90.67, 94, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'jefferson_marcelo08@gmail.com'), 5);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 79.16, CURRENT_DATE-1, 93.75, 100, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'andreia_de_lima13@gmail.com'), 6);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 73.21, CURRENT_DATE-1, 91.96, 100, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'jose_raimundo09@gmail.com'), 7);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 79.16, CURRENT_DATE-1, 88.15, 92, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'andreia_de_lima13@gmail.com'), 7);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 83.91, CURRENT_DATE-1, 91.67, 95, 2, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'alecsander_camilo05@gmail.com'), 8);
INSERT INTO INSCRICAO VALUES((SELECT NEXTVAL('SEQUENCE_ID_INSCRICAO')), 45.62, CURRENT_DATE-1, 62.69, 70, 1, 'AGUARDANDO', (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'josilete_rodrigues14@gmail.com'), 8);