-- Inserindo perfis de usuario
INSERT INTO PERFIL VALUES ((SELECT NEXT VALUE FOR SEQUENCE_ID_PERFIL), 'ADMIN');
INSERT INTO PERFIL VALUES ((SELECT NEXT VALUE FOR SEQUENCE_ID_PERFIL), 'COORDENADOR');
INSERT INTO PERFIL VALUES ((SELECT NEXT VALUE FOR SEQUENCE_ID_PERFIL), 'ALUNO');

-- Senha: 123456
-- $2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu
-- Hasheada com BCrypt. Secret está no application.yml de testes


-- Inserindo usuario admin do sistema
INSERT INTO USUARIO VALUES ((SELECT NEXT VALUE FOR SEQUENCE_ID_USUARIO), '2022-05-11', 'admin@gmail.com', '20171370011', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'ADMIN'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'admin@gmail.com'));

-- Inserindo um coordenador
INSERT INTO USUARIO VALUES ((SELECT NEXT VALUE FOR SEQUENCE_ID_USUARIO), '2022-05-11', 'coordenador_01@gmail.com', '20171370012', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME LIKE 'COORDENADOR'), (SELECT ID FROM USUARIO WHERE LOGIN LIKE 'coordenador_01@gmail.com'));

-- Inserindo um aluno
INSERT INTO USUARIO VALUES ((SELECT NEXT VALUE FOR SEQUENCE_ID_USUARIO), '2022-05-11', 'aluno_01@gmail.com', '20221370003', '$2a$10$F/f76piJUaBdGsDlJ9dHD.yyxOUSWMY/bYob3Kwqx9whgIJ3hP1pu');
INSERT INTO USUARIOS_PERFIS VALUES ((SELECT ID FROM PERFIL WHERE NOME = 'ALUNO'), (SELECT ID FROM USUARIO WHERE LOGIN = 'aluno_01@gmail.com'));